### ISSUE TITLE
add opened and closed events

### ISSUE THREAD

**Issue by bugwelle** [jakiestfu/Snap.js#104]
Hello,
it seems that there isn't a `opened` oder `closed` event. The events that are currently available (`open` and `close`) aren't fired when dragging the sidebar.

I'd like to have these two events:
- `opened` : fired when sidebar has opened
- `closed` : fired when sidebar has closed

Or am I missing something in the current version, that does what I'd like to see? :)

Greetings from Germany,
Andre

**Comment by ftorre104** [comment]
+1

**Comment by takrishna** [comment]
Opened and closed will definitely help.

Though temporarily solution can be:

I think you can use the drawer state to get the opened/closed events. 

Try something like snapper.on('open')
{
check the state of drawer - if done opening
}

**Comment by bugwelle** [comment]
Well, the `open` event is not fired if the user drags the content. Only if a button is pressed. :)

**Comment by ftorre104** [comment]
You can do snapper.on(animated) and then check if the state is open. Thats what i ended up using. It checks at the end of the animation whether it is open  or not. 

```
Cheers,

—
```

**Comment by ftorre104** [comment]
**\* the state will be "closed" "left" or "right" -- not open  if i remember correctly. 

```
—
```

**Comment by prud** [comment]
Agree, listen for 'animated' event and check the state afterwards.

**Comment by bugwelle** [comment]
Thanks,
I hadn't tried that. It works :)

**Comment by longlostnick** [comment]
Listening for 'animated' isn't ideal because it also gets fired when touching the panel, even if the menu is already closed. If I'm checking to see if the state is closed in the animated callback and the menu is already closed it will return true, when what I really want to know is that the menu was OPEN and it became closed. I can add an extra boolean to keep my own state of whether or not the menu is already open, but that seems overly complex just to avoid adding an opened/closed event.
