### ISSUE TITLE
Strange logic you have implemented

### ISSUE THREAD

**Issue by iuliangcata** [jakiestfu/Snap.js#224]
Why would one want to duplicate the content on both sides, and not have different content on every side ? I was struggling to achieve this, but it seems impossible.

**Comment by frankie-loves-jesus** [comment]
> Why would one want to duplicate the content on both sides
- Swiping from left to right to open menu is the defacto standard on all mobile devices
- However, it's easier for users (the majority of which are right-handed) to swipe from right to left due to the placement of their thumb and the way they hold their mobile devices
- Overall navigation is also simplified by encouraging a single menu as opposed to two

> and nod have different content on every side ? I was struggling to achieve this, but it seems impossible. 

Just fill out `<div class="snap-drawer snap-drawer-right">`. By leaving it empty, the menu will be duplicated on both sides.

Having said that, you need to provide us with a test case. Please see [CSS Tricks - Reduced Test Cases](http://css-tricks.com/reduced-test-cases/) on why they _"are the absolute, ... number one way to troubleshoot bugs."_
- A reduced test case is an isolated example that demonstrates the bug or issue.
- It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug. No extra functionality or styling.
- A link to your site is not a reduced test case.

**Comment by frankie-loves-jesus** [comment]
Could you close this @enr00ted?
