### ISSUE TITLE
Ratchet + Snap.js dosent work in android browser (Jelly Bean)

### ISSUE THREAD

**Issue by novium** [jakiestfu/Snap.js#26]
Ratchet + Snap.js dosent work in android browser (Jelly Bean). Snap.js only works perfectly!

**Comment by jakiestfu** [comment]
I don't believe Ratchet works on Android devices, does it? Does Ratchet work in Jelly Bean by itself without Snap.js?

**Comment by novium** [comment]
Ratchet works on Android,
Ratchet + Snap,js dosent

**Comment by jakiestfu** [comment]
Excuse my simplistic questions. Are you using the demo provided in the repo? Do you know what kind of errors are happening if any?

**Comment by jakiestfu** [comment]
@Zoidberrg Bump

**Comment by jakiestfu** [comment]
No evidence or support has been provided regarding this issue.

**Comment by stefreak** [comment]
I can confirm that Snap.js is broken on Android + Ratchet (tested on Nexus 4 + Phonegap). The problem is, that the content and header bar does not get pushed to left or right by the menu bar.

It seems that translate3d has no effect on fixed positioned elements on the android browser and Ratchet uses `position:fixed` for almost anything.

I simply replaced any occurrence of `position:fixed` with `position:absolute` in `ratchet.css` and it works fine for me. I don't know if this has any undesired side effects.

**Comment by nolandubeau** [comment]
I have encountered the same issue but the css change did not appear to fix my issue.  i'm just getting familiar with the android emulator/sdk's and using phonegap to build for android. it may very well be an issue with my setup.

**Comment by nolandubeau** [comment]
Correction.  My find and replace didn't work.  The above CSS did resolve the issue.  Thank you!

**Comment by stefreak** [comment]
You're welcome! :)

**Comment by novium** [comment]
I switched to bootstrap with a lot of custom css (to remove bootstrap feeling) ;)
