### ISSUE TITLE
Android 2.3.x Webkit scrolling problems

### ISSUE THREAD

**Issue by grigio** [jakiestfu/Snap.js#33]
- The left side menu isn't scrollable
- "no drag area" drags

probably it is related to webkit 2.3.x limitations and a solution could integrate something similar for these devices:
http://lab.cubiq.org/iscroll/examples/simple/
https://github.com/cubiq/iscroll

**Comment by prud** [comment]
It might be a bit of an overkill to actually add a dependency just for the sake of the demo menu being scrollable.

Just have a note somewhere saying that the demos use overflow-scrolling which is not supported on older mobile browsers (both iOS and Android) and that JS scrolling (e.g. iScroll) is compatible with Snap.js.

**Comment by grigio** [comment]
I see, so I suggest to explicitly say "Partial support for Android WebKit 2.3.X+" in the readme

**Comment by jakiestfu** [comment]
@grigio @prud I've gotten snap working on 2.3.5 (no overflow), but I do not know at which version overflow support begins

**Comment by prud** [comment]
In my opinion it doesn't matter at which version overflow scrolling starts, because it is not a required feature Snap.is.    Developers can decide on their own whether they want to use overflow scrolling or implement it with a JS plugin .. Just make sure to include the minimum required OS version for the particular functionality of your script (dragging, snapping, using all the options, ..).
What you might want to do is adding a hint that the demos use overflow scroll which might not be supported on all browsers that support Snap.is itself. Then link to your preferred JS scrolling frameworks.

**Comment by jakiestfu** [comment]
@prud Thanks for the advice. I will go ahead and mention that in the Readme, and as for the other initial problem opened by @grigio, please reference issue #32 in regards to fixing the ignored elements. It is not fixed yet but will be soon
