### ISSUE TITLE
Sliders combined with Snap.js

### ISSUE THREAD

**Issue by lmartins** [jakiestfu/Snap.js#35]
Is there any way to prevent Snap.js normal behaviour when the user is trying to drag a slider interface inside the main content?

One option viable in my case would to only allow Snap.js dragging on the title bar.

Thanks.

**Comment by racorbit** [comment]
That's the way I went.
—
Rick

**Comment by lmartins** [comment]
@racorbit Could you share how you did it?
Thanks!

**Comment by racorbit** [comment]
Sorry about that I thought you were looming for a better way.  I just add the data-ignore-snap=true attribute to every element I don't want snap to listen for swipes, before I call snap on the content area.  Make sure you put ignore and all the child elements too, which is why I do it in js and just html.

That's how I do it for now, but will eventually modify snap so it accepts an option for ignoring child elements, for a more elegant solution.
—
Rick

**Comment by lmartins** [comment]
Thanks Rick, i'll try that.
Direct targeting the element to control de slide would be awesome though. That way we could have only the title-bar watching for drag events related to the drawers.

Cheers.

**Comment by jakiestfu** [comment]
@racorbit @lmartins I have already gotten Snap.js to work with a touch slider, and that has a lot to do with `data-snap-ignore` and intent, but referencing Issue #32, this problem will probably be fixed. That being said, with the next major release, I will include a FAQ page in the Wiki or Readme that explains how to target specific elements as your drag handle (such as the title bar). Let this issue cross over to #32 and we will solve it there.
